### ISSUE TITLE
Tide Team and Contributor badging process

### ISSUE THREAD

**Issue by jeffpaul** [wptide/wptide#170]
## Issue Overview

Tide doesn't have a defined process for how Tide Team and Tide Contributor badges are credited for those maintaining or contributing.

## Steps to Reproduce (for bugs)

n/a

## Expected Behavior

Tide has a documented process for awarding badges, gets current with badges that should be in place at the moment, and follows the process into the future.

## Current Behavior

Nothing exists on this for Tide.

## Possible Solution

A [good example exists from the Community Team](https://make.wordpress.org/community/2017/08/21/recent-profile-badge-changes/), so we can leverage that to draft one for Tide.

## Todos

- [x] Decide where the process info should live (wptide readme, docs site, make/tide handbook)
- [x] Create badge images
- [x] Draft and publish process info ([draft started here](https://docs.google.com/document/d/15H_kRwbVyR11mDQHe0VqUj7rjvdWHilQwFK41wEk_FM/edit))
- [x] Create Meta Trac ticket ([see Community Team example](https://meta.trac.wordpress.org/ticket/3036)) to establish [Associations/Groups](https://profiles.wordpress.org/associations/) and credit existing Team and Contributors
- [x] Add Tide to [Profile Badges page on make/meta](https://make.wordpress.org/meta/handbook/documentation/profile-badges/)
- [x] Draft and publish announcement post on make/tide ([see Community Team example](https://make.wordpress.org/community/2017/08/21/recent-profile-badge-changes/))

**Comment by jeffpaul** [comment]
Initial list of team/contributors: https://github.com/wptide/wptide#credits

**Comment by jeffpaul** [comment]
Here's the color palette  to use when creating any images:

![tide colour palette](https://user-images.githubusercontent.com/2818133/49702017-6eb9ec00-fbb9-11e8-8bbc-20994e65acd2.png)

**Comment by cathibosco** [comment]
The art files are needed in a few places - badges, dashicons, pins etc etc....  Here are 2 master files, one is #1526FF and the other is black - from dashicon collection. I have asked the design team inside trello board to assist with making sure the proper files get to all of the proper places. 
[Tide.zip](https://github.com/wptide/wptide/files/2687058/Tide.zip)

**Comment by jeffpaul** [comment]
Awesome, thank you @cathibosco!  Mind linking into the design trello board to the specific task on this so we can see when that's done and ready for us to continue working to resolve this for Tide?

**Comment by cathibosco** [comment]
I just added the link to this issue to our Trello card - is that what I should have done? @jeffpaul

**Comment by jeffpaul** [comment]
@cathibosco can you share the link to the design trello card here as well?

**Comment by cathibosco** [comment]
Sure! https://trello.com/c/FPWBhnod/155-tide-icon-is-ready-tide-team-icon-is-complete-we-need-to-add-it-to-a-few-places-in-the-ecosystem-for-the-team

**Comment by jeffpaul** [comment]
Note that as part of contributions at WCUS Contributor Day, we'll want to make sure we badge the following once we have Contributor badging setup:
- kkoppenhaver
- croixhaug
- pwtyler

**Comment by cathibosco** [comment]
Status Update: The Meta team pointed out a couple of wayward anchor points in the vector file. I made the adjustments and did edit the file a bit so this is now the current version - waiting to hear back again  to see if they will be able to approve it now. I feel strongly that it will move forward now... Attached are the simplified "master" versions thus far: 
[Tide-simplified.zip](https://github.com/wptide/wptide/files/2703257/Tide-simplified.zip)

**Comment by coffee2code** [comment]
As a followup: now that the Tide dashicon was added for WP 5.2, the following tasks have been completed:

* Badges for Tide Team and Tide Contributor have been created.
* Badges have been assigned to users (per [meta4157](https://meta.trac.wordpress.org/ticket/4157#comment:2) and the [comment above](https://github.com/wptide/wptide/issues/170#issuecomment-449092737)).
* Tide was added to the [Profile Badges page on make/meta](https://make.wordpress.org/meta/handbook/documentation/profile-badges/).

As for input about where to publish the more detailed criteria for the badge, there has been discussion to request that each team publish a page about it in their handbook (see [#meta527](https://meta.trac.wordpress.org/ticket/527)). It hasn't been fully decided or standardized yet (i.e. what the page should be titled).

Having the page reside in the make/tide handbook seems most logical since it is the WordPress.org hub for contributors to that team (even if in this particular case the team may be more active in GitHub). We'll probably end up linking to such a handbook page from a few places eventually (the profile badges themselves, the make/meta handbook listing of badges, etc).

**Comment by jeffpaul** [comment]
@cathibosco feel like you've got bandwidth to take the draft process doc linked in the original description and get that polished akin to the Community Team announcement and publish on Make/Tide by the end of June?  We're starting to get some smaller contributions and would be good to have a defined credit/props/badging process defined (ideally by WCEU for folks who show up to Contributor Day there).

**Comment by cathibosco** [comment]
I will take a look! @jeffpaul

**Comment by cathibosco** [comment]
@jeffpaul - 

1. The badges are styled up with CSS... Here is a screenshot with inspector. https://canddstudios.d.pr/EChxdf
2. I suggested edits to the doc here: https://docs.google.com/document/d/15H_kRwbVyR11mDQHe0VqUj7rjvdWHilQwFK41wEk_FM/edit#heading=h.u0p5gsihqj1g
3. Missing is a "handbook" and please review the edits I suggested... I am not sure the links to the pages I suggested are optimal or if a handbook is needed.

**Comment by jeffpaul** [comment]
@cathibosco in place of a "handbook", I think we can utilize the [documentation site](https://wptide.org) and find the best place there to host this info.

**Comment by jeffpaul** [comment]
@cathibosco I'm thinking `Profile Badges` can be a section at the end of https://www.wptide.org/contributing.  Seem good to you?

**Comment by jeffpaul** [comment]
Just published the announcement on make/tide: https://make.wordpress.org/tide/2019/06/20/tide-profile-badges/

**Comment by cathibosco** [comment]
Well done @jeffpaul - Love the Tide Documentation site!

**Comment by jeffpaul** [comment]
Closing as the final items were resolved in https://github.com/wptide/docs/pull/35.
