### ISSUE TITLE
Publish public roadmap

### ISSUE THREAD

**Issue by jeffpaul** [wptide/wptide#79]
- [x] setup ZenHub structure in `go-tide` repo
- [x] setup wiki details in `go-tide` repo
- [x] setup ZenHub structure in `wptide` org
- [ ] ~setup wiki details in `wptide` org~
- [ ] publish make/xwp and/or make/tide post announcing roadmap

**Comment by jeffpaul** [comment]
Will begin migrating to `wptide` org when we've pushed this repo to that org.

**Comment by jeffpaul** [comment]
@RobStino I believe you had noted something about a blog post announcing the Tide update to v1.0 and the demo/docs site. Is that something you can help craft to publish before/during/after WCEU (timing as you see most reasonable).

**Comment by jeffpaul** [comment]
Per [bugscrub](https://wordpress.slack.com/archives/C7TK8FBUJ/p1534882684000100) today, we're tagging this to be completed during the `1.0.0` release timeline

**Comment by jeffpaul** [comment]
Note that we're not going to utilize GitHub's wiki and instead are hosting related content on wptide.org

**Comment by jeffpaul** [comment]
This issue will be fully resolved once https://github.com/wptide/docs/pull/16 gets merged.

**Comment by jeffpaul** [comment]
Note that this issue was [referenced in Slack](https://wordpress.slack.com/archives/C7TK8FBUJ/p1543353059091500).

**Comment by jeffpaul** [comment]
Closing this as done with a note that once we complete the PHP Compat work that we'll re-cast for ideas on what to focus on next for Tide and will publish that request and resulting roadmap on [Make/Tide](https://make.wordpress.org/tide/).
